### ISSUE TITLE
-role not working as intended

### ISSUE THREAD

**Issue by Hyperfresh8080** [Hyperfresh8080/CAutomator#3]
Suspected culprit: bot.py - lines 121 to 123:
`if message.content.startswith('-role'):
        print(str(member.roles))
        if(lvl30ID in member.roles): # check if the member has level 30 role`

Problem: assumed to not be detecting Level 30+ role properly. I'm assuming it's something with the check `if(lvl30id in member.roles)` and not finding what it's supposed to find.

**Comment by iwaQwQ** [comment]
i'll make a fix for that today, don't seems to be something hard to resolve

**Comment by Hyperfresh8080** [comment]
i managed to find a fix @iwaQwQ, dw :)

**Comment by iwaQwQ** [comment]
@Hyperfresh8080 actually you broke something with the `delrole` command :/

(https://github.com/Hyperfresh8080/CAutomator/pull/4#discussion_r419093207)
