### ISSUE TITLE
license invalid

### ISSUE THREAD

**Issue by iwa** [Hyperfresh8080/CAutomator#9]
you broke your license file by adding the line :

https://github.com/Hyperfresh8080/CAutomator/blob/d21eaac047a0519855f5658a625c5db40177b94a/LICENSE#L12

you don't need to add it since the license already state that condition :
![Screen Shot 2020-05-11 at 10 17 12](https://user-images.githubusercontent.com/19956672/81539482-96921e00-9370-11ea-95c6-bd02323e508d.png)

**Comment by Hyperfresh8080** [comment]
Removed license for now as per #10, I'm planning to find a license other than MIT but I may revert back to MIT anyway lol. We'll see.

**Comment by Hyperfresh8080** [comment]
Now fixed as per e42a1a2. I've moved the code over to LGPLv3.
